apiVersion: apps/v1
kind: Deployment
metadata:
  name: acs730-web
  labels:
    app: acs730-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: acs730-web
  template:
    metadata:
      labels:
        app: acs730-web
    spec:
      containers:
        - name: web
          image: ghcr.io/leolu-teach/acs730-lab4:latest
          ports:
            - containerPort: 5000
